# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'user_interface_version0Xywlwc.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QAbstractSpinBox, QApplication, QCheckBox,
    QDialogButtonBox, QFrame, QGroupBox, QHeaderView,
    QLCDNumber, QLabel, QListWidget, QListWidgetItem,
    QMainWindow, QPushButton, QSizePolicy, QSlider,
    QSpinBox, QStatusBar, QTabWidget, QTableWidget,
    QTableWidgetItem, QTextEdit, QWidget)

class Ui_DetectWindows(object):
    def setupUi(self, DetectWindows):
        if not DetectWindows.objectName():
            DetectWindows.setObjectName(u"DetectWindows")
        DetectWindows.resize(997, 768)
        self.centralwidget = QWidget(DetectWindows)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 1011, 731))
        self.tabWidget.setTabPosition(QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QTabWidget.TabShape.Rounded)
        self.tab_MainMonitor = QWidget()
        self.tab_MainMonitor.setObjectName(u"tab_MainMonitor")
        self.groupBox_Screen = QGroupBox(self.tab_MainMonitor)
        self.groupBox_Screen.setObjectName(u"groupBox_Screen")
        self.groupBox_Screen.setGeometry(QRect(10, 70, 821, 631))
        self.frame_Detection = QLabel(self.groupBox_Screen)
        self.frame_Detection.setObjectName(u"frame_Detection")
        self.frame_Detection.setGeometry(QRect(10, 20, 800, 600))
        self.frame_Detection.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame_Detection.setFrameShadow(QFrame.Shadow.Raised)
        self.frame_Detection.setScaledContents(True)

        self.groupBox_Production_model = QGroupBox(self.tab_MainMonitor)
        self.groupBox_Production_model.setObjectName(u"groupBox_Production_model")
        self.groupBox_Production_model.setGeometry(QRect(10, 0, 971, 71))
        self.label_Model_Name = QLabel(self.groupBox_Production_model)
        self.label_Model_Name.setObjectName(u"label_Model_Name")
        self.label_Model_Name.setGeometry(QRect(10, 20, 551, 41))
        self.label_Model_Name.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_Model_Name.setTextFormat(Qt.TextFormat.PlainText)
        self.label_Model_Name.setScaledContents(True)
        self.label_Model_Name.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.line = QFrame(self.groupBox_Production_model)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(570, 20, 16, 41))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_Classes = QLabel(self.groupBox_Production_model)
        self.label_Classes.setObjectName(u"label_Classes")
        self.label_Classes.setGeometry(QRect(590, 20, 371, 41))
        self.label_Classes.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_Classes.setScaledContents(True)
        self.label_Classes.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_2 = QLabel(self.tab_MainMonitor)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(920, 180, 541, 41))
        self.label_2.setTextFormat(Qt.TextFormat.PlainText)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.groupBox_Setting = QGroupBox(self.tab_MainMonitor)
        self.groupBox_Setting.setObjectName(u"groupBox_Setting")
        self.groupBox_Setting.setGeometry(QRect(840, 70, 141, 531))
        self.checkBox_signal_Alarm = QCheckBox(self.groupBox_Setting)
        self.checkBox_signal_Alarm.setObjectName(u"checkBox_signal_Alarm")
        self.checkBox_signal_Alarm.setGeometry(QRect(20, 350, 101, 20))
        self.checkBox_SoundAlarm = QCheckBox(self.groupBox_Setting)
        self.checkBox_SoundAlarm.setObjectName(u"checkBox_SoundAlarm")
        self.checkBox_SoundAlarm.setGeometry(QRect(20, 380, 101, 20))
        self.checkBox_DigitalOut = QCheckBox(self.groupBox_Setting)
        self.checkBox_DigitalOut.setObjectName(u"checkBox_DigitalOut")
        self.checkBox_DigitalOut.setGeometry(QRect(20, 410, 101, 20))
        self.checkBox_DigitalIN = QCheckBox(self.groupBox_Setting)
        self.checkBox_DigitalIN.setObjectName(u"checkBox_DigitalIN")
        self.checkBox_DigitalIN.setGeometry(QRect(20, 440, 101, 20))
        self.checkBox_Blank3 = QCheckBox(self.groupBox_Setting)
        self.checkBox_Blank3.setObjectName(u"checkBox_Blank3")
        self.checkBox_Blank3.setGeometry(QRect(20, 470, 101, 20))
        self.checkBox_blank4 = QCheckBox(self.groupBox_Setting)
        self.checkBox_blank4.setObjectName(u"checkBox_blank4")
        self.checkBox_blank4.setGeometry(QRect(20, 500, 101, 20))
        self.label_confident = QLabel(self.groupBox_Setting)
        self.label_confident.setObjectName(u"label_confident")
        self.label_confident.setGeometry(QRect(10, 92, 81, 31))
        self.label_confident.setFrameShadow(QFrame.Shadow.Raised)
        self.label_confident.setScaledContents(False)
        self.label_confident.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.spinBox_confident = QSpinBox(self.groupBox_Setting)
        self.spinBox_confident.setObjectName(u"spinBox_confident")
        self.spinBox_confident.setGeometry(QRect(10, 120, 121, 23))
        self.spinBox_confident.setReadOnly(False)
        self.spinBox_confident.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.PlusMinus)
        self.spinBox_confident.setMinimum(1)
        self.spinBox_confident.setMaximum(100)
        self.spinBox_confident.setValue(70)
        self.pushButton_connect = QPushButton(self.groupBox_Setting)
        self.pushButton_connect.setObjectName(u"pushButton_connect")
        self.pushButton_connect.setGeometry(QRect(10, 20, 121, 31))
        self.pushButton_disconnect = QPushButton(self.groupBox_Setting)
        self.pushButton_disconnect.setObjectName(u"pushButton_disconnect")
        self.pushButton_disconnect.setGeometry(QRect(10, 54, 121, 31))
        self.horizontalSlider_confident = QSlider(self.groupBox_Setting)
        self.horizontalSlider_confident.setObjectName(u"horizontalSlider_confident")
        self.horizontalSlider_confident.setGeometry(QRect(10, 150, 121, 20))
        self.horizontalSlider_confident.setMinimum(1)
        self.horizontalSlider_confident.setMaximum(100)
        self.horizontalSlider_confident.setValue(70)
        self.horizontalSlider_confident.setOrientation(Qt.Orientation.Horizontal)
        self.lcdNumber_CheckOK = QLCDNumber(self.groupBox_Setting)
        self.lcdNumber_CheckOK.setObjectName(u"lcdNumber_CheckOK")
        self.lcdNumber_CheckOK.setGeometry(QRect(10, 200, 121, 51))
        self.lcdNumber_CheckOK.setAutoFillBackground(True)
        self.label_CheckOK = QLabel(self.groupBox_Setting)
        self.label_CheckOK.setObjectName(u"label_CheckOK")
        self.label_CheckOK.setGeometry(QRect(10, 170, 121, 31))
        self.label_CheckOK.setFrameShadow(QFrame.Shadow.Raised)
        self.label_CheckOK.setScaledContents(False)
        self.label_CheckOK.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_CheckNG = QLabel(self.groupBox_Setting)
        self.label_CheckNG.setObjectName(u"label_CheckNG")
        self.label_CheckNG.setGeometry(QRect(10, 260, 121, 31))
        self.label_CheckNG.setFrameShadow(QFrame.Shadow.Raised)
        self.label_CheckNG.setScaledContents(False)
        self.label_CheckNG.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lcdNumber_CheckNG = QLCDNumber(self.groupBox_Setting)
        self.lcdNumber_CheckNG.setObjectName(u"lcdNumber_CheckNG")
        self.lcdNumber_CheckNG.setGeometry(QRect(10, 290, 121, 51))
        font = QFont()
        font.setBold(False)
        self.lcdNumber_CheckNG.setFont(font)
        self.lcdNumber_CheckNG.setAutoFillBackground(True)
        self.lcdNumber_CheckNG.setFrameShadow(QFrame.Shadow.Raised)
        self.lcdNumber_CheckNG.setSegmentStyle(QLCDNumber.SegmentStyle.Filled)
        self.label_Logo = QLabel(self.tab_MainMonitor)
        self.label_Logo.setObjectName(u"label_Logo")
        self.label_Logo.setGeometry(QRect(840, 600, 141, 91))
        self.label_Logo.setPixmap(QPixmap(u"../Universal_AI2/agc-logo-png-transparent-logo-v2.png"))
        self.label_Logo.setScaledContents(True)
        self.label_Logo.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.tab_MainMonitor, "")
        self.tab_Model_Matching = QWidget()
        self.tab_Model_Matching.setObjectName(u"tab_Model_Matching")
        self.groupBox_Model_match_making = QGroupBox(self.tab_Model_Matching)
        self.groupBox_Model_match_making.setObjectName(u"groupBox_Model_match_making")
        self.groupBox_Model_match_making.setGeometry(QRect(10, 0, 981, 651))
        self.groupBox_Model_match_making.setFlat(False)
        self.groupBox_Model_match_making.setCheckable(False)
        self.groupBox_Browse_Yolo = QGroupBox(self.groupBox_Model_match_making)
        self.groupBox_Browse_Yolo.setObjectName(u"groupBox_Browse_Yolo")
        self.groupBox_Browse_Yolo.setGeometry(QRect(610, 20, 351, 511))
        self.label_yolo_model = QLabel(self.groupBox_Browse_Yolo)
        self.label_yolo_model.setObjectName(u"label_yolo_model")
        self.label_yolo_model.setGeometry(QRect(20, 27, 221, 51))
        self.label_yolo_model.setFrameShape(QFrame.Shape.Panel)
        self.label_yolo_model.setWordWrap(True)
        self.buttonBox_yolo_open_apply = QDialogButtonBox(self.groupBox_Browse_Yolo)
        self.buttonBox_yolo_open_apply.setObjectName(u"buttonBox_yolo_open_apply")
        self.buttonBox_yolo_open_apply.setGeometry(QRect(250, 20, 81, 61))
        self.buttonBox_yolo_open_apply.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.buttonBox_yolo_open_apply.setOrientation(Qt.Orientation.Vertical)
        self.buttonBox_yolo_open_apply.setStandardButtons(QDialogButtonBox.StandardButton.Apply|QDialogButtonBox.StandardButton.Open)
        self.buttonBox_yolo_open_apply.setCenterButtons(True)
        self.listWidget = QListWidget(self.groupBox_Browse_Yolo)
        self.listWidget.setObjectName(u"listWidget")
        self.listWidget.setGeometry(QRect(20, 90, 321, 411))
        self.groupBox_Model = QGroupBox(self.groupBox_Model_match_making)
        self.groupBox_Model.setObjectName(u"groupBox_Model")
        self.groupBox_Model.setGeometry(QRect(20, 20, 571, 621))
        self.tableWidget_model_match = QTableWidget(self.groupBox_Model)
        if (self.tableWidget_model_match.columnCount() < 4):
            self.tableWidget_model_match.setColumnCount(4)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget_model_match.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget_model_match.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget_model_match.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget_model_match.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        self.tableWidget_model_match.setObjectName(u"tableWidget_model_match")
        self.tableWidget_model_match.setGeometry(QRect(10, 20, 551, 551))
        self.tableWidget_model_match.setFrameShape(QFrame.Shape.StyledPanel)
        self.tableWidget_model_match.setFrameShadow(QFrame.Shadow.Plain)
        self.tableWidget_model_match.setShowGrid(True)
        self.tableWidget_model_match.setGridStyle(Qt.PenStyle.SolidLine)
        self.tableWidget_model_match.setSortingEnabled(True)
        self.tableWidget_model_match.setCornerButtonEnabled(True)
        self.tableWidget_model_match.setRowCount(0)
        self.tableWidget_model_match.setColumnCount(4)
        self.tableWidget_model_match.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_model_match.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget_model_match.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_model_match.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_model_match.verticalHeader().setProperty(u"showSortIndicator", True)
        self.tableWidget_model_match.verticalHeader().setStretchLastSection(False)
        self.buttonBox_save_cancel_apply = QDialogButtonBox(self.groupBox_Model)
        self.buttonBox_save_cancel_apply.setObjectName(u"buttonBox_save_cancel_apply")
        self.buttonBox_save_cancel_apply.setGeometry(QRect(350, 570, 211, 41))
        self.buttonBox_save_cancel_apply.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.buttonBox_save_cancel_apply.setOrientation(Qt.Orientation.Horizontal)
        self.buttonBox_save_cancel_apply.setStandardButtons(QDialogButtonBox.StandardButton.Apply|QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Save)
        self.buttonBox_save_cancel_apply.setCenterButtons(True)
        self.pushButton_add_model = QPushButton(self.groupBox_Model)
        self.pushButton_add_model.setObjectName(u"pushButton_add_model")
        self.pushButton_add_model.setGeometry(QRect(10, 577, 75, 24))
        self.pushButton_remove_model = QPushButton(self.groupBox_Model)
        self.pushButton_remove_model.setObjectName(u"pushButton_remove_model")
        self.pushButton_remove_model.setGeometry(QRect(90, 577, 75, 24))
        self.groupBox_DigitalOutput = QGroupBox(self.groupBox_Model_match_making)
        self.groupBox_DigitalOutput.setObjectName(u"groupBox_DigitalOutput")
        self.groupBox_DigitalOutput.setGeometry(QRect(610, 540, 351, 101))
        self.label_OK_output = QLabel(self.groupBox_DigitalOutput)
        self.label_OK_output.setObjectName(u"label_OK_output")
        self.label_OK_output.setGeometry(QRect(20, 20, 101, 31))
        self.label_OK_output.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_OK_output.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_NG_output = QLabel(self.groupBox_DigitalOutput)
        self.label_NG_output.setObjectName(u"label_NG_output")
        self.label_NG_output.setGeometry(QRect(20, 60, 101, 31))
        self.label_NG_output.setFrameShape(QFrame.Shape.StyledPanel)
        self.label_NG_output.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.textEdit_OK_output_script = QTextEdit(self.groupBox_DigitalOutput)
        self.textEdit_OK_output_script.setObjectName(u"textEdit_OK_output_script")
        self.textEdit_OK_output_script.setGeometry(QRect(130, 20, 211, 31))
        self.textEdit_NG_output_script = QTextEdit(self.groupBox_DigitalOutput)
        self.textEdit_NG_output_script.setObjectName(u"textEdit_NG_output_script")
        self.textEdit_NG_output_script.setGeometry(QRect(130, 60, 211, 31))
        self.label_5 = QLabel(self.tab_Model_Matching)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(920, 650, 71, 46))
        self.label_5.setPixmap(QPixmap(u"../Universal_AI2/agc-logo-png-transparent-logo-v2.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.tab_Model_Matching, "")
        DetectWindows.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(DetectWindows)
        self.statusbar.setObjectName(u"statusbar")
        DetectWindows.setStatusBar(self.statusbar)

        self.retranslateUi(DetectWindows)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(DetectWindows)
    # setupUi

    def retranslateUi(self, DetectWindows):
        DetectWindows.setWindowTitle(QCoreApplication.translate("DetectWindows", u"MainWindow", None))
        self.groupBox_Screen.setTitle(QCoreApplication.translate("DetectWindows", u"Screen", None))
        self.groupBox_Production_model.setTitle(QCoreApplication.translate("DetectWindows", u"Production Model", None))
        self.label_Model_Name.setText(QCoreApplication.translate("DetectWindows", u"Model Name", None))
        self.label_Classes.setText(QCoreApplication.translate("DetectWindows", u"Lead / Lead Free", None))
        self.label_2.setText(QCoreApplication.translate("DetectWindows", u"Model Name", None))
        self.groupBox_Setting.setTitle(QCoreApplication.translate("DetectWindows", u"Setting", None))
        self.checkBox_signal_Alarm.setText(QCoreApplication.translate("DetectWindows", u"Signal Alarm", None))
        self.checkBox_SoundAlarm.setText(QCoreApplication.translate("DetectWindows", u"Sound Alarm", None))
        self.checkBox_DigitalOut.setText(QCoreApplication.translate("DetectWindows", u"Digital Out", None))
        self.checkBox_DigitalIN.setText(QCoreApplication.translate("DetectWindows", u"Digital In", None))
        self.checkBox_Blank3.setText(QCoreApplication.translate("DetectWindows", u"blank #3", None))
        self.checkBox_blank4.setText(QCoreApplication.translate("DetectWindows", u"blank #4", None))
        self.label_confident.setText(QCoreApplication.translate("DetectWindows", u"Confident =", None))
        self.spinBox_confident.setSuffix(QCoreApplication.translate("DetectWindows", u"%", None))
        self.pushButton_connect.setText(QCoreApplication.translate("DetectWindows", u"Connect", None))
        self.pushButton_disconnect.setText(QCoreApplication.translate("DetectWindows", u"Disconnect", None))
        self.label_CheckOK.setText(QCoreApplication.translate("DetectWindows", u"Check OK Qty =", None))
        self.label_CheckNG.setText(QCoreApplication.translate("DetectWindows", u"Check NG Qty =", None))
        self.label_Logo.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_MainMonitor), QCoreApplication.translate("DetectWindows", u"Main Monitor", None))
        self.groupBox_Model_match_making.setTitle(QCoreApplication.translate("DetectWindows", u"Model Match Making", None))
        self.groupBox_Browse_Yolo.setTitle(QCoreApplication.translate("DetectWindows", u"Browse Yolo Model", None))
        self.label_yolo_model.setText(QCoreApplication.translate("DetectWindows", u"Select Yolo Model (.pt)", None))
        self.groupBox_Model.setTitle(QCoreApplication.translate("DetectWindows", u"GroupBox", None))
        ___qtablewidgetitem = self.tableWidget_model_match.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("DetectWindows", u"Name", None));
        ___qtablewidgetitem1 = self.tableWidget_model_match.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("DetectWindows", u"Classes", None));
        ___qtablewidgetitem2 = self.tableWidget_model_match.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("DetectWindows", u"Status", None));
        ___qtablewidgetitem3 = self.tableWidget_model_match.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("DetectWindows", u"Barcode", None));
        self.pushButton_add_model.setText(QCoreApplication.translate("DetectWindows", u"Add", None))
        self.pushButton_remove_model.setText(QCoreApplication.translate("DetectWindows", u"Remove", None))
        self.groupBox_DigitalOutput.setTitle(QCoreApplication.translate("DetectWindows", u"Digital Output", None))
        self.label_OK_output.setText(QCoreApplication.translate("DetectWindows", u"OK Output", None))
        self.label_NG_output.setText(QCoreApplication.translate("DetectWindows", u"NG Output", None))
        self.label_5.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Model_Matching), QCoreApplication.translate("DetectWindows", u"Model Matching", None))
    # retranslateUi

